version: 2

workflows:
  version: 2
  ci:
    jobs:
    - lint
    - build
    - test-readme

jobs:
  lint:
    docker:
      - image: grafana/cortex-jsonnet-build-image:3527936
    steps:
      - checkout
      - run:
          name: "Check white noise"
          command: make check-white-noise
      - run:
          name: "Lint mixin"
          command: make lint-mixin
      - run:
          name: "Lint playbooks"
          command: make lint-playbooks

  build:
    docker:
      - image: grafana/cortex-jsonnet-build-image:3527936
    steps:
      - checkout
      - run: make build-mixin
      - store_artifacts:
          path: cortex-mixin/cortex-mixin.zip

  test-readme:
    docker:
      - image: grafana/cortex-jsonnet-build-image:3527936
    steps:
      - checkout
      - run: make test-readme
